package api

import (
	"database/sql"
	"log"
	"net/http"

	"github.com/4lerman/pm_service/internal/service/projects"
	"github.com/4lerman/pm_service/internal/service/tasks"
	"github.com/4lerman/pm_service/internal/service/users"
	"github.com/gorilla/mux"

	_ "github.com/4lerman/pm_service/docs" // Import the docs generated by Swag CLI
	httpSwagger "github.com/swaggo/http-swagger"
)

type APIServer struct {
	addr string
	db   *sql.DB
}

func NewAPIServer(addr string, db *sql.DB) *APIServer {
	return &APIServer{
		addr: addr,
		db:   db,
	}
}


// @title Project Management Service
// @version 1.0
// @description This is a API server for project management service.
// @host localhost:5000
// @BasePath /api/v1
func (s *APIServer) Run() error {
	router := mux.NewRouter()

	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)


	subRouter := router.PathPrefix("/api/v1").Subrouter()

	usersRouter := subRouter.PathPrefix("/users").Subrouter()
	tasksRouter := subRouter.PathPrefix("/tasks").Subrouter()
	projectsRouter := subRouter.PathPrefix("/projects").Subrouter()

	usersStore := users.NewStore(s.db)
	usersService := users.NewHandler(usersStore)
	usersService.RegisterRoutes(usersRouter)

	tasksStore := tasks.NewStore(s.db)
	tasksService := tasks.NewHandler(tasksStore)
	tasksService.RegisterRoutes(tasksRouter)

	projectsStore := projects.NewStore(s.db)
	projectsService := projects.NewHandler(projectsStore)
	projectsService.RegisterRoutes(projectsRouter)

	log.Println("Listening on", s.addr)
	return http.ListenAndServe(s.addr, router)
}
